DATA: 
  CLASS_NAME_FILE: 'configs/namefiles/coco.names'
  AUGMENT: '3'

  TRAIN:
    IMG_DIR: 'data/funsd/training_data/images' #训练图片
    LAB_DIR: 'data/FUNSD/training_data/annotations'

  TEST:
    IMG_DIR: 'data/FUNSD/testing_data/images'
    LAB_DIR: 'data/FUNSD/testing_data/annotations'


DETECTOR: #在这里填入需要的检测器
  NAME: ["PS_IC15", "DB_r50","DBPP_r50"] #,"PANET_IC15","PANET_CTW","textsnake","DB_r50","DBPP_r50"
  

ATTACKER:
  METHOD: "optim"
  EPSILON: 0.09 #patch epsilon，和PATCH_ATTACK.EPSILON保持一致
  MAX_EPOCH: 1000
  ITER_STEP: 1

  STEP_SIZE: 0.005
  TARGET_CLASS:
  ATTACK_CLASS: '0' # 不用管
  LOSS_FUNC: "obj-tv" # [null, 'descend-mse', 'ascend-mse', 'obj', 'obj-tv']
  tv_eta: 0 #tv-loss的权重
  obj_eta: 1 #conf-loss的权重
  scheduler: 'ALRS'
  START_LEARNING_RATE: 0.03

  PATCH_ATTACK:
    WIDTH: 300
    HEIGHT: 300
    EPSILON: 0.09 #patch epsilon，和ATTACKER.EPSILON保持一致
    INIT: "zero" # ['random', 'zero']
    ASPECT_RATIO: 1 # 不用管